version: '2'
services:
  teamcity-server:
    image: teamcity-server:local-linux
    ports:
     - "8112:8111"

  teamcity-agent-dotnet:
    image: teamcity-agent:linux-dotnet
    privileged: true
    environment:
      - SERVER_URL=teamcity-server:8111
      - DOCKER_IN_DOCKER=start